id: I99F828F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:31:08+00:00'
last_modified: '2022-06-08T08:53:11.605314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20411
  title: སྙན་ངག་མེ་ལོང་གི་ཟིན་ཐོ་དྲན་པའི་གསལ་འདེབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    488B:
      image_group_id: I5703
      title: ''
      total_pages: 326
      order: 1
      base_file: 488B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
