id: P009137
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20411
  title: སྙན་ངག་མེ་ལོང་གི་ཟིན་ཐོ་དྲན་པའི་གསལ་འདེབས
  author: ''
  volumes:
    563ee853af9e41db9c6dd351db2cf314:
      image_group_id: I5703
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
